import React, { useState } from 'react';
import {
  Users,
  Sparkles,
  CheckCircle2,
  Clock,
  ArrowRight,
  Plus,
  FileText,
  Calendar,
  Layers,
  Check,
  AlertCircle
} from 'lucide-react';
import confetti from 'canvas-confetti';
import { MeetingRecord, ActionItem } from '../types';

interface MeetingsViewProps {
  meeting: MeetingRecord;
  onSummarizeMeeting: (transcript: string, title: string, date: string) => Promise<any>;
  onApproveActionAsTask: (action: ActionItem) => void;
}

export const MeetingsView: React.FC<MeetingsViewProps> = ({
  meeting,
  onSummarizeMeeting,
  onApproveActionAsTask,
}) => {
  const [activeTab, setActiveTab] = useState<'summary' | 'transcript' | 'new'>('summary');
  const [currentMeeting, setCurrentMeeting] = useState<MeetingRecord>(meeting);
  const [isLoading, setIsLoading] = useState(false);

  // New transcript state
  const [newTitle, setNewTitle] = useState('Design Team & Structural Coordination Meeting #09');
  const [newDate, setNewDate] = useState('2026-08-25');
  const [newTranscript, setNewTranscript] = useState('');

  const handleRunSummarizer = async () => {
    setIsLoading(true);
    try {
      const result = await onSummarizeMeeting(
        currentMeeting.rawTranscript,
        currentMeeting.title,
        currentMeeting.date
      );

      if (result) {
        setCurrentMeeting(prev => ({
          ...prev,
          summary: result.summary || prev.summary,
          decisions: result.decisions || prev.decisions,
          actionItems: result.actionItems || prev.actionItems,
        }));
      }
    } finally {
      setIsLoading(false);
    }
  };

  const handleRunNewTranscript = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTranscript.trim()) return;

    setIsLoading(true);
    try {
      const result = await onSummarizeMeeting(newTranscript, newTitle, newDate);

      if (result) {
        setCurrentMeeting({
          id: `MTG-${Date.now().toString().slice(-3)}`,
          title: newTitle,
          date: newDate,
          location: 'Site Boardroom',
          chairperson: 'David Sterling (PM)',
          attendees: ['Refilwe Mathebe', 'David Sterling', 'Liam Burke', 'Marcus Vance'],
          rawTranscript: newTranscript,
          summary: result.summary || 'Summary generated by AI.',
          decisions: result.decisions || [],
          actionItems: result.actionItems || [],
          sourceDocumentRef: 'Uploaded Transcript Audio Record',
        });
        setActiveTab('summary');
      }
    } finally {
      setIsLoading(false);
    }
  };

  const handleApproveAction = (action: ActionItem) => {
    onApproveActionAsTask(action);
    // Update local state
    setCurrentMeeting(prev => ({
      ...prev,
      actionItems: prev.actionItems.map(a => 
        a.id === action.id ? { ...a, isApprovedAsTask: true } : a
      ),
    }));
    confetti({
      particleCount: 40,
      spread: 50,
      origin: { y: 0.8 },
    });
  };

  const unapprovedCount = currentMeeting.actionItems.filter(a => !a.isApprovedAsTask).length;

  return (
    <div className="max-w-6xl mx-auto space-y-6 pb-12">
      {/* Header */}
      <div className="bg-white rounded-xl border border-slate-200 p-5 shadow-xs">
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
          <div>
            <div className="flex items-center space-x-2">
              <span className="bg-blue-100 text-blue-800 text-xs font-mono font-semibold px-2 py-0.5 rounded">
                {currentMeeting.id}
              </span>
              <span className="text-xs text-slate-500 font-mono">
                Date: {currentMeeting.date}
              </span>
            </div>
            <h2 className="font-display text-2xl font-bold text-slate-900 mt-1">
              {currentMeeting.title}
            </h2>
            <div className="flex flex-wrap items-center gap-x-3 text-xs text-slate-500 mt-1">
              <span><strong>Chair:</strong> {currentMeeting.chairperson}</span>
              <span>•</span>
              <span><strong>Attendees:</strong> {currentMeeting.attendees.length} Commercial & Engineering Leads</span>
            </div>
          </div>

          <div className="flex items-center space-x-2">
            <div className="flex items-center bg-slate-100 p-1 rounded-xl text-xs font-semibold">
              <button
                onClick={() => setActiveTab('summary')}
                className={`px-3 py-1.5 rounded-lg transition-all cursor-pointer ${
                  activeTab === 'summary' ? 'bg-white text-slate-900 shadow-xs' : 'text-slate-600 hover:text-slate-900'
                }`}
              >
                Decisions & Actions ({currentMeeting.actionItems.length})
              </button>
              <button
                onClick={() => setActiveTab('transcript')}
                className={`px-3 py-1.5 rounded-lg transition-all cursor-pointer ${
                  activeTab === 'transcript' ? 'bg-white text-slate-900 shadow-xs' : 'text-slate-600 hover:text-slate-900'
                }`}
              >
                Raw Transcript
              </button>
              <button
                onClick={() => setActiveTab('new')}
                className={`px-3 py-1.5 rounded-lg transition-all cursor-pointer flex items-center space-x-1 ${
                  activeTab === 'new' ? 'bg-white text-slate-900 shadow-xs' : 'text-slate-600 hover:text-slate-900'
                }`}
              >
                <Plus className="w-3.5 h-3.5" />
                <span>New Notes</span>
              </button>
            </div>

            <button
              onClick={handleRunSummarizer}
              disabled={isLoading}
              className="bg-blue-600 hover:bg-blue-700 disabled:opacity-50 text-white text-xs font-semibold px-3 py-2 rounded-lg flex items-center space-x-1.5 transition-all shadow-xs cursor-pointer"
            >
              <Sparkles className="w-3.5 h-3.5 text-blue-200" />
              <span>{isLoading ? 'Processing AI Summary...' : 'Re-Summarize with AI'}</span>
            </button>
          </div>
        </div>
      </div>

      {/* TAB 1: Structured AI Summary, Decisions & Actions */}
      {activeTab === 'summary' && (
        <div className="space-y-6">
          {/* Executive Summary Card */}
          <div className="bg-white rounded-xl border border-slate-200 p-5 shadow-xs space-y-2">
            <h3 className="font-display font-bold text-base text-slate-900 flex items-center space-x-2">
              <FileText className="w-4 h-4 text-blue-600" />
              <span>Executive Meeting Summary</span>
            </h3>
            <p className="text-xs text-slate-700 leading-relaxed max-w-4xl">
              {currentMeeting.summary}
            </p>
          </div>

          {/* Grid: Formal Decisions & Action Items */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* Approved Decisions */}
            <div className="bg-white rounded-xl border border-slate-200 p-5 shadow-xs space-y-4">
              <div className="flex items-center justify-between border-b border-slate-100 pb-2">
                <h3 className="font-display font-bold text-sm text-slate-900 flex items-center space-x-2">
                  <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                  <span>Approved Formal Decisions ({currentMeeting.decisions.length})</span>
                </h3>
                <span className="text-[10px] font-mono bg-emerald-50 text-emerald-800 px-2 py-0.5 rounded font-semibold">
                  Binding Minutes
                </span>
              </div>

              <div className="space-y-2.5">
                {currentMeeting.decisions.map((dec, i) => (
                  <div
                    key={i}
                    className="bg-slate-50 border border-slate-100 rounded-lg p-3 text-xs text-slate-800 flex items-start space-x-2"
                  >
                    <span className="font-mono text-emerald-700 font-bold shrink-0">#{i + 1}</span>
                    <span className="leading-relaxed">{dec}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Action Items with Human Approval to Task */}
            <div className="bg-white rounded-xl border border-slate-200 p-5 shadow-xs space-y-4">
              <div className="flex items-center justify-between border-b border-slate-100 pb-2">
                <div>
                  <h3 className="font-display font-bold text-sm text-slate-900 flex items-center space-x-2">
                    <Clock className="w-4 h-4 text-blue-600" />
                    <span>Action Items Plan ({currentMeeting.actionItems.length})</span>
                  </h3>
                  <p className="text-[11px] text-slate-500">
                    Drafts remain unassigned until approved by human QS/PM.
                  </p>
                </div>

                {unapprovedCount > 0 ? (
                  <span className="text-[10px] font-mono bg-amber-100 text-amber-800 px-2 py-0.5 rounded font-semibold">
                    {unapprovedCount} Drafts
                  </span>
                ) : (
                  <span className="text-[10px] font-mono bg-emerald-100 text-emerald-800 px-2 py-0.5 rounded font-semibold">
                    All Approved
                  </span>
                )}
              </div>

              <div className="space-y-3">
                {currentMeeting.actionItems.map((act) => (
                  <div
                    key={act.id}
                    className={`rounded-lg p-3 border text-xs space-y-2 transition-all ${
                      act.isApprovedAsTask
                        ? 'bg-emerald-50/40 border-emerald-200'
                        : 'bg-white border-slate-200 hover:border-blue-300'
                    }`}
                  >
                    <div className="flex items-center justify-between">
                      <span className="font-mono font-bold text-slate-600">{act.id}</span>
                      <span className={`text-[10px] font-semibold px-2 py-0.5 rounded ${
                        act.priority === 'high' ? 'bg-rose-100 text-rose-800' :
                        act.priority === 'medium' ? 'bg-amber-100 text-amber-800' :
                        'bg-slate-100 text-slate-700'
                      }`}>
                        {act.priority.toUpperCase()} • {act.category}
                      </span>
                    </div>

                    <p className="text-xs text-slate-800 font-medium leading-relaxed">
                      {act.description}
                    </p>

                    <div className="pt-2 border-t border-slate-100 flex items-center justify-between text-[11px] text-slate-500">
                      <div>
                        <span>Owner: <strong className="text-slate-700">{act.owner}</strong></span>
                        <span className="ml-2 font-mono text-slate-600">Due: {act.deadline}</span>
                      </div>

                      {act.isApprovedAsTask ? (
                        <span className="text-emerald-700 font-bold text-[11px] flex items-center space-x-1">
                          <Check className="w-3.5 h-3.5" />
                          <span>Live in Kanban</span>
                        </span>
                      ) : (
                        <button
                          onClick={() => handleApproveAction(act)}
                          className="bg-blue-600 hover:bg-blue-700 text-white text-[11px] font-semibold px-2.5 py-1 rounded flex items-center space-x-1 cursor-pointer transition-colors"
                        >
                          <Plus className="w-3 h-3" />
                          <span>Approve as Task</span>
                        </button>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      )}

      {/* TAB 2: Raw Transcript Viewer */}
      {activeTab === 'transcript' && (
        <div className="bg-white rounded-xl border border-slate-200 p-5 shadow-xs space-y-3">
          <div className="flex items-center justify-between border-b border-slate-100 pb-2">
            <h3 className="font-display font-bold text-base text-slate-900">
              Verbatim Meeting Transcript & Audio Ingestion Log
            </h3>
            <span className="text-xs text-slate-500 font-mono">{currentMeeting.sourceDocumentRef}</span>
          </div>

          <pre className="p-4 bg-slate-900 text-slate-200 rounded-lg text-xs font-mono whitespace-pre-wrap leading-relaxed max-h-[500px] overflow-y-auto">
            {currentMeeting.rawTranscript}
          </pre>
        </div>
      )}

      {/* TAB 3: Ingest New Transcript */}
      {activeTab === 'new' && (
        <div className="bg-white rounded-xl border border-slate-200 p-5 shadow-xs space-y-4">
          <h3 className="font-display font-bold text-base text-slate-900">
            Ingest & Summarize New Meeting Transcript
          </h3>

          <form onSubmit={handleRunNewTranscript} className="space-y-3 text-xs">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label className="block font-semibold text-slate-700 mb-1">Meeting Title</label>
                <input
                  type="text"
                  required
                  value={newTitle}
                  onChange={(e) => setNewTitle(e.target.value)}
                  className="w-full px-3 py-2 border border-slate-200 rounded-lg text-xs"
                />
              </div>
              <div>
                <label className="block font-semibold text-slate-700 mb-1">Meeting Date</label>
                <input
                  type="date"
                  required
                  value={newDate}
                  onChange={(e) => setNewDate(e.target.value)}
                  className="w-full px-3 py-2 border border-slate-200 rounded-lg text-xs font-mono"
                />
              </div>
            </div>

            <div>
              <label className="block font-semibold text-slate-700 mb-1">Paste Audio Transcript or Meeting Notes</label>
              <textarea
                rows={10}
                required
                placeholder="Paste verbatim transcript with speaker timestamps or typed meeting bullet points..."
                value={newTranscript}
                onChange={(e) => setNewTranscript(e.target.value)}
                className="w-full px-3 py-2 border border-slate-200 rounded-lg text-xs font-mono"
              />
            </div>

            <button
              type="submit"
              disabled={isLoading}
              className="bg-blue-600 hover:bg-blue-700 disabled:opacity-50 text-white font-semibold px-4 py-2.5 rounded-lg flex items-center space-x-2 transition-all cursor-pointer"
            >
              <Sparkles className="w-4 h-4 text-blue-200" />
              <span>{isLoading ? 'Extracting Decisions & Actions...' : 'Process Transcript with AI'}</span>
            </button>
          </form>
        </div>
      )}
    </div>
  );
};
